version: "3"
services:
  integration:
    build:
      context: .
    environment:
      INSIDE_CONTAINER: 'true'
    command: dockerize -wait tcp://platform:8080 -wait tcp://broker:61613 -timeout 3m npm run jest-integration
    depends_on:
      - platform
  platformdata:
    build:
      context: .
    environment:
      INSIDE_CONTAINER: 'true'
      TRELLIS_BASE_URL: http://platform:8080
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-us-west-2_CGd9Wq136}
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION:-us-west-2}
    command: dockerize -wait tcp://platform:8080 -timeout 3m bin/migrate
    depends_on:
      - platform
  backupusers:
    build:
      context: .
    environment:
      TRELLIS_BASE_URL: http://platform:8080
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION:-us-west-2}
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}" # add to .env file (DO NOT CHECK IN)
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}" # add to .env file (DO NOT CHECK IN)
    command: bin/backup_users
  platform:
    image: ld4p/trellis-ext-db:latest
    environment:
      TRELLIS_BASE_URL: http://platform:8080
      TRELLIS_LOGGING_LEVEL: INFO
      TRELLIS_CONSOLE_LOGGING_THRESHOLD: INFO
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-us-west-2_CGd9Wq136}
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION:-us-west-2}
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
      - broker
      - migration
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: sinopia
      POSTGRES_DB: sinopia
      POSTGRES_PASSWORD: S1n0p1a
      PGDATA: /var/lib/postgresql/data/pgdata/mydata
    ports:
      - 5432:5432
  broker:
    image: rmohr/activemq
    ports:
      - 61613:61613
  migration:
    image: ld4p/trellis-ext-db:latest
    command: ["/opt/trellis/bin/trellis-db", "db", "migrate", "/opt/trellis/etc/config.yml"]
    depends_on:
      - database
