version: "3"
services:
  integration:
    build:
      context: .
    environment:
      INSIDE_CONTAINER: 'true'
    command: dockerize -wait tcp://platform:8080 -wait tcp://broker:61613 -timeout 3m npm run jest-integration
    depends_on:
      - platform
  platform:
    image: ld4p/trellis-ext-db:latest
    environment:
      TRELLIS_BASE_URL: http://platform:8080
      TRELLIS_LOGGING_LEVEL: INFO
      TRELLIS_CONSOLE_LOGGING_THRESHOLD: INFO
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - database
      - broker
      - migration
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: sinopia
      POSTGRES_DB: sinopia
      POSTGRES_PASSWORD: S1n0p1a
      PGDATA: /var/lib/postgresql/data/pgdata/mydata
    ports:
      - 5432:5432
  broker:
    image: rmohr/activemq
    ports:
      - 61613:61613
  migration:
    image: ld4p/trellis-ext-db:latest
    command: ["/opt/trellis/bin/trellis-db", "db", "migrate", "/opt/trellis/etc/config.yml"]
    depends_on:
      - database
